// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4WOxSwpIJ6IlJrosP3_DpIBYzR69XR6U',
    appId: '1:871277061461:android:8b19604dc7a4e56f19fbdc',
    messagingSenderId: '871277061461',
    projectId: 'authtutorial-f1e34',
    storageBucket: 'authtutorial-f1e34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Gw73IGCMZQctzW4xIROyTV0e2NawCGU',
    appId: '1:871277061461:ios:2b08f5783d365b0919fbdc',
    messagingSenderId: '871277061461',
    projectId: 'authtutorial-f1e34',
    storageBucket: 'authtutorial-f1e34.appspot.com',
    androidClientId: '871277061461-hn5o154qd4bhblcusiousqmfna66dvqk.apps.googleusercontent.com',
    iosClientId: '871277061461-7nri8ii6fdava6gkgvvo5nom8dqhr6n9.apps.googleusercontent.com',
    iosBundleId: 'com.duytq.flutterchatdemo',
  );

}